### ISSUE TITLE
Arduino Pro Micro 

### ISSUE THREAD

**Issue by apom** [bootsector/XBOXPadMicro#1]
Hi,
it's not an issue,
I ordered some Pro Micro instead of Micro arduinos,
and I changed the mapping to use them for an arcade controler (without the analog inputs).

![promicro](https://user-images.githubusercontent.com/4094314/41594139-b0a62c70-73c2-11e8-9362-c71566a5f595.png)

Here is the new main.c file and the hex file:
[XBOXPadMicro_proMicro.zip](https://github.com/bootsector/XBOXPadMicro/files/2114961/XBOXPadMicro_proMicro.zip)

If this can help someone...

**Comment by kabone** [comment]
Works fantastically! Thanks!

**Comment by Itzusman** [comment]
hi. very nice project plzz plzz plzz can you add the Dpad in it plzzzz? i only want buttons left stick and dpad. i am not good with coding plzzzzz help me make a hex for Promicro plzzzz

**Comment by bootsector** [comment]
Hi!

Please try the mod made by Imp from the following thread:

http://forum.arcadecontrols.com/index.php/topic,152687.80.html

Cheers,

bootsector

**Comment by Itzusman** [comment]
Hi I needed for Xbox original. This is for Xbox 360
