### ISSUE TITLE
i have pro micro plzzz help me

### ISSUE THREAD

**Issue by Itzusman** [bootsector/XBOXPadMicro#2]
hi. very nice project plzz plzz plzz can you add the Dpad in it plzzzz? i only want buttons left stick and dpad. i am not good with coding plzzzzz help me make a hex for Promicro plzzzz

my email is    itzme,usman@gmail.com

**Comment by bootsector** [comment]
Hi!

Please try the mod made by Imp from the following thread:

http://forum.arcadecontrols.com/index.php/topic,152687.80.html

Cheers,

bootsector
